version: '3.0'
services:
  activeMQ:
    image: rmohr/activemq:5.12.0
    user: root
    ports:
      - 61616:61616
      - 8161:8161
    networks:
     - mensageria-net
    volumes:
      - mq-data:/opt/activemq/data/

networks:
  mensageria-net:

volumes:
  mq-data:
